use chrono::Utc;
use cron::Schedule;
use rusqlite::{params, Connection, OptionalExtension};
use serde::{Deserialize, Serialize};
use std::{collections::HashMap, fs, path::PathBuf, sync::{Arc, Mutex}, thread, time::Duration, io::Write, str::FromStr};
use std::process::Command;
use tauri::{AppHandle, Emitter, Manager, State};
#[derive(Serialize)] struct CliResult { ok: bool, message: String }
struct Db(Arc<Mutex<Connection>>);
#[derive(Serialize)] struct TaskRow { id:String, name:String, repo:String, cron:String, agents:String, status:String }
#[derive(Deserialize)] struct NewTask { id:String, name:String, repo:String, cron:String, agents:Vec<String> }

 fn migrate(conn: &Connection) -> rusqlite::Result<()> { conn.execute_batch("PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS tasks (id TEXT PRIMARY KEY, name TEXT NOT NULL, repo TEXT NOT NULL, cron TEXT NOT NULL, agents TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'queued', created_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS events (id INTEGER PRIMARY KEY, kind TEXT NOT NULL, message TEXT NOT NULL, created_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS repos (name TEXT PRIMARY KEY, path TEXT NOT NULL, provider TEXT NOT NULL DEFAULT 'local'); CREATE TABLE IF NOT EXISTS thread_messages (id INTEGER PRIMARY KEY, repo TEXT NOT NULL, author TEXT NOT NULL, body TEXT NOT NULL, created_at TEXT NOT NULL); CREATE INDEX IF NOT EXISTS idx_thread_messages_repo ON thread_messages(repo, created_at); CREATE TABLE IF NOT EXISTS notifications (id TEXT PRIMARY KEY, provider TEXT NOT NULL, repo TEXT NOT NULL, title TEXT NOT NULL, body TEXT NOT NULL, url TEXT NOT NULL, author TEXT NOT NULL, unread INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL); CREATE INDEX IF NOT EXISTS idx_notifications_created ON notifications(created_at DESC); CREATE TABLE IF NOT EXISTS provider_settings (provider TEXT PRIMARY KEY, url TEXT NOT NULL);") }

#[tauri::command]
fn run_agent_cli(provider: String, prompt: String, repo_path: String, db: State<Db>, app: AppHandle) -> CliResult { let message = format!("Queued {provider} task for {repo_path}: {prompt}"); if let Ok(conn)=db.0.lock(){let _=conn.execute("INSERT INTO events(kind,message,created_at) VALUES (?1,?2,?3)",params!["agent.queued",message,Utc::now().to_rfc3339()]);} let _=app.emit("wand://agent", message.clone()); CliResult { ok: true, message } }

#[tauri::command]
fn create_task(task: NewTask, db: State<Db>) -> Result<(),String> { let conn=db.0.lock().map_err(|e|e.to_string())?; conn.execute("INSERT OR REPLACE INTO tasks(id,name,repo,cron,agents,status,created_at) VALUES (?1,?2,?3,?4,?5,'queued',?6)",params![task.id,task.name,task.repo,task.cron,serde_json::to_string(&task.agents).map_err(|e|e.to_string())?,Utc::now().to_rfc3339()]).map_err(|e|e.to_string())?; Ok(()) }

#[tauri::command]
fn list_tasks(db: State<Db>) -> Result<Vec<TaskRow>,String> { let conn=db.0.lock().map_err(|e|e.to_string())?; let mut stmt=conn.prepare("SELECT id,name,repo,cron,agents,status FROM tasks ORDER BY created_at DESC").map_err(|e|e.to_string())?; let rows=stmt.query_map([],|r|Ok(TaskRow{id:r.get(0)?,name:r.get(1)?,repo:r.get(2)?,cron:r.get(3)?,agents:r.get(4)?,status:r.get(5)?})).map_err(|e|e.to_string())?; rows.map(|r|r.map_err(|e|e.to_string())).collect() }

#[derive(Serialize)] struct ThreadMessage { id:i64, repo:String, author:String, body:String, created_at:String }
#[tauri::command]
fn list_thread_messages(repo:String, db:State<Db>)->Result<Vec<ThreadMessage>,String>{let conn=db.0.lock().map_err(|e|e.to_string())?; let mut stmt=conn.prepare("SELECT id,repo,author,body,created_at FROM thread_messages WHERE repo=?1 ORDER BY id ASC").map_err(|e|e.to_string())?; let rows=stmt.query_map(params![repo],|r|Ok(ThreadMessage{id:r.get(0)?,repo:r.get(1)?,author:r.get(2)?,body:r.get(3)?,created_at:r.get(4)?})).map_err(|e|e.to_string())?; rows.map(|r|r.map_err(|e|e.to_string())).collect()}
#[tauri::command]
fn create_thread_message(repo:String, author:String, body:String, db:State<Db>, app:AppHandle)->Result<ThreadMessage,String>{let body=body.trim().to_string(); if body.is_empty(){return Err("Message cannot be empty".into())} let created_at=Utc::now().to_rfc3339(); let conn=db.0.lock().map_err(|e|e.to_string())?; conn.execute("INSERT INTO thread_messages(repo,author,body,created_at) VALUES (?1,?2,?3,?4)",params![repo,author,body,created_at]).map_err(|e|e.to_string())?; let id=conn.last_insert_rowid(); let message=ThreadMessage{id,repo,author,body,created_at}; let _=app.emit("wand://thread",&message); Ok(message)}

#[derive(Serialize)] struct NotificationRow { id:String, provider:String, repo:String, title:String, body:String, url:String, author:String, unread:bool, created_at:String }
#[tauri::command]
fn list_notifications(db:State<Db>)->Result<Vec<NotificationRow>,String>{let conn=db.0.lock().map_err(|e|e.to_string())?; let mut stmt=conn.prepare("SELECT id,provider,repo,title,body,url,author,unread,created_at FROM notifications ORDER BY created_at DESC LIMIT 100").map_err(|e|e.to_string())?; let rows=stmt.query_map([],|r|Ok(NotificationRow{id:r.get(0)?,provider:r.get(1)?,repo:r.get(2)?,title:r.get(3)?,body:r.get(4)?,url:r.get(5)?,author:r.get(6)?,unread:r.get::<_,i64>(7)?!=0,created_at:r.get(8)?})).map_err(|e|e.to_string())?; rows.map(|r|r.map_err(|e|e.to_string())).collect()}
#[tauri::command]
fn mark_notifications_read(db:State<Db>)->Result<(),String>{let conn=db.0.lock().map_err(|e|e.to_string())?; conn.execute("UPDATE notifications SET unread=0",[]).map_err(|e|e.to_string())?; Ok(())}

#[derive(Serialize)] struct CliStatus { id:String, name:String, command:String, installed:bool, version:String }
#[tauri::command]
fn detect_clis() -> Vec<CliStatus> { let specs=[("claude","Claude","claude"),("codex","Codex","codex"),("kimi","Kimi","kimi"),("gemini","Gemini CLI","gemini")]; specs.iter().map(|(id,name,cmd)|{let path=Command::new("sh").args(["-lc",&format!("command -v {cmd}")]).output().ok().filter(|o|o.status.success()).map(|o|String::from_utf8_lossy(&o.stdout).trim().to_string()); let version=Command::new(cmd).arg("--version").output().ok().map(|o|String::from_utf8_lossy(&o.stdout).lines().next().unwrap_or("").to_string()).unwrap_or_default(); CliStatus{id:id.to_string(),name:name.to_string(),command:cmd.to_string(),installed:path.is_some(),version}}).collect() }
fn provider_service(provider:&str)->Result<&'static str,String>{match provider{"github"=>Ok("wand-github-pat"),"azure-devops"=>Ok("wand-azure-devops-pat"),_=>Err("Unsupported provider".into())}}
#[tauri::command]
fn save_provider_token(provider:String, token:String)->Result<(),String>{if token.trim().is_empty(){return Err("Token cannot be empty".into())} let service=provider_service(&provider)?; let entry=keyring::Entry::new(service,"default").map_err(|e|e.to_string())?; entry.set_password(&token).map_err(|e|e.to_string())}
#[tauri::command]
fn provider_status(provider:String)->Result<bool,String>{let service=provider_service(&provider)?; let entry=keyring::Entry::new(service,"default").map_err(|e|e.to_string())?; Ok(entry.get_password().is_ok())}
#[tauri::command]
fn save_provider_url(provider:String, url:String, db:State<Db>)->Result<(),String>{let value=url.trim().trim_end_matches('/').to_string(); if value.is_empty(){return Err("Provider URL cannot be empty".into())} if provider!="azure-devops"{return Err("Only Azure DevOps organization URLs are configurable".into())} let conn=db.0.lock().map_err(|e|e.to_string())?; conn.execute("INSERT OR REPLACE INTO provider_settings(provider,url) VALUES (?1,?2)",params![provider,value]).map_err(|e|e.to_string())?; Ok(())}
#[tauri::command]
fn provider_url(provider:String, db:State<Db>)->Result<Option<String>,String>{let conn=db.0.lock().map_err(|e|e.to_string())?; conn.query_row("SELECT url FROM provider_settings WHERE provider=?1",params![provider],|r|r.get(0)).optional().map_err(|e|e.to_string())}
#[derive(Deserialize)] struct ChainRequest { task_id:String, prompt:String, repo_path:String, agents:Vec<String>, cli:String }
fn allowed_cli(cli:&str)->Option<&'static str>{match cli{"claude"=>Some("claude"),"codex"=>Some("codex"),"kimi"=>Some("kimi"),"gemini"=>Some("gemini"),_=>None}}
#[tauri::command]
fn run_agent_chain(req:ChainRequest, db:State<Db>, app:AppHandle)->Result<(),String>{let command=allowed_cli(&req.cli).ok_or_else(||"Unsupported CLI".to_string())?.to_string(); let db_arc=db.0.clone(); thread::spawn(move||{for (index,agent) in req.agents.iter().enumerate(){let _=app.emit("wand://agent",serde_json::json!({"task_id":req.task_id,"agent":agent,"stage":index+1,"status":"running"})); let mut child=match Command::new(&command).current_dir(&req.repo_path).arg("--print").arg(&req.prompt).stdin(std::process::Stdio::piped()).stdout(std::process::Stdio::piped()).spawn(){Ok(c)=>c,Err(e)=>{let _=app.emit("wand://agent",serde_json::json!({"task_id":req.task_id,"agent":agent,"status":"failed","error":e.to_string()}));return}}; if let Some(mut stdin)=child.stdin.take(){let _=stdin.write_all(format!("You are the {agent} stage. Complete your part, then summarize the handoff for the next agent.\n").as_bytes());} let output=child.wait_with_output(); match output{Ok(out) if out.status.success()=>{if let Ok(conn)=db_arc.lock(){let _=conn.execute("INSERT INTO events(kind,message,created_at) VALUES (?1,?2,?3)",params!["agent.completed",format!("{agent} completed stage {}",index+1),Utc::now().to_rfc3339()]);} let _=app.emit("wand://agent",serde_json::json!({"task_id":req.task_id,"agent":agent,"stage":index+1,"status":"completed","handoff":String::from_utf8_lossy(&out.stdout)}));},Ok(out)=>{let _=app.emit("wand://agent",serde_json::json!({"task_id":req.task_id,"agent":agent,"status":"failed","error":String::from_utf8_lossy(&out.stderr)}));return},Err(e)=>{let _=app.emit("wand://agent",serde_json::json!({"task_id":req.task_id,"agent":agent,"status":"failed","error":e.to_string()}));return}}} let _=app.emit("wand://agent",serde_json::json!({"task_id":req.task_id,"status":"verified"}));}); Ok(())}
#[derive(Clone, Serialize)]
struct SyncEvent { source: String, message: String, timestamp: String }

#[derive(Serialize)] struct ProviderRepo { name:String, path:String, provider:String, url:String }
async fn provider_token(provider:&str)->Result<String,String>{let service=provider_service(provider)?; let entry=keyring::Entry::new(service,"default").map_err(|e|e.to_string())?; entry.get_password().map_err(|e|e.to_string())}
#[tauri::command]
async fn sync_github(db:State<'_,Db>, app:AppHandle)->Result<Vec<ProviderRepo>,String>{let token=provider_token("github").await?; let response=reqwest::Client::new().get("https://api.github.com/user/repos?per_page=100&sort=updated").header("User-Agent","Wand").bearer_auth(token).send().await.map_err(|e|e.to_string())?; if !response.status().is_success(){return Err(format!("GitHub returned {}",response.status()))} let repos:Vec<serde_json::Value>=response.json().await.map_err(|e|e.to_string())?; let mut out=Vec::new(); let conn=db.0.lock().map_err(|e|e.to_string())?; for repo in repos{let name=repo["full_name"].as_str().unwrap_or_default().to_string(); let url=repo["html_url"].as_str().unwrap_or_default().to_string(); let path=repo["clone_url"].as_str().unwrap_or_default().to_string(); if name.is_empty(){continue} conn.execute("INSERT OR REPLACE INTO repos(name,path,provider) VALUES (?1,?2,'github')",params![name,path]).map_err(|e|e.to_string())?; out.push(ProviderRepo{name,path,provider:"github".into(),url});} let _=app.emit("wand://provider",serde_json::json!({"provider":"github","count":out.len()})); Ok(out)}
#[tauri::command]
async fn sync_github_activity(db:State<'_,Db>, app:AppHandle)->Result<u32,String>{let token=provider_token("github").await?; let names:Vec<String>={let conn=db.0.lock().map_err(|e|e.to_string())?; let mut stmt=conn.prepare("SELECT name FROM repos WHERE provider='github'").map_err(|e|e.to_string())?; let rows=stmt.query_map([],|r|r.get(0)).map_err(|e|e.to_string())?; let result=rows.collect::<Result<Vec<String>,_>>().map_err(|e|e.to_string())?; result}; let client=reqwest::Client::new(); let mut added=0; for name in names{let endpoint=format!("https://api.github.com/repos/{name}/issues/comments?per_page=50&sort=created&direction=desc"); let response=client.get(endpoint).header("User-Agent","Wand").bearer_auth(&token).send().await.map_err(|e|e.to_string())?; if !response.status().is_success(){continue} let comments:Vec<serde_json::Value>=response.json().await.map_err(|e|e.to_string())?; for comment in comments{let id=format!("github:{}",comment["id"].as_i64().unwrap_or(0)); let issue_url=comment["issue_url"].as_str().unwrap_or_default(); let issue_response=client.get(issue_url).header("User-Agent","Wand").bearer_auth(&token).send().await.map_err(|e|e.to_string())?; let issue:serde_json::Value=issue_response.json().await.unwrap_or_default(); if issue["pull_request"].is_null(){continue} let conn=db.0.lock().map_err(|e|e.to_string())?; let changed=conn.execute("INSERT OR IGNORE INTO notifications(id,provider,repo,title,body,url,author,unread,created_at) VALUES (?1,'github',?2,?3,?4,?5,?6,1,?7)",params![id,name,issue["title"].as_str().unwrap_or("Pull request comment"),comment["body"].as_str().unwrap_or_default(),comment["html_url"].as_str().unwrap_or_default(),comment["user"]["login"].as_str().unwrap_or("GitHub"),comment["created_at"].as_str().unwrap_or_default()]).map_err(|e|e.to_string())?; if changed>0{added+=1;}}} let _=app.emit("wand://notifications",serde_json::json!({"provider":"github","added":added})); Ok(added)}
#[tauri::command]
async fn sync_azure_devops(provider_url:String, db:State<'_,Db>, app:AppHandle)->Result<Vec<ProviderRepo>,String>{let token=provider_token("azure-devops").await?; let endpoint=provider_url.trim_end_matches('/').to_string()+"/_apis/git/repositories?api-version=7.1"; let response=reqwest::Client::new().get(endpoint).basic_auth("",Some(token)).send().await.map_err(|e|e.to_string())?; if !response.status().is_success(){return Err(format!("Azure DevOps returned {}",response.status()))} let payload:serde_json::Value=response.json().await.map_err(|e|e.to_string())?; let mut out=Vec::new(); let conn=db.0.lock().map_err(|e|e.to_string())?; for repo in payload["value"].as_array().cloned().unwrap_or_default(){let name=repo["name"].as_str().unwrap_or_default().to_string(); let url=repo["webUrl"].as_str().unwrap_or_default().to_string(); let path=repo["remoteUrl"].as_str().unwrap_or_default().to_string(); if name.is_empty(){continue} conn.execute("INSERT OR REPLACE INTO repos(name,path,provider) VALUES (?1,?2,'azure-devops')",params![name,path]).map_err(|e|e.to_string())?; out.push(ProviderRepo{name,path,provider:"azure-devops".into(),url});} let _=app.emit("wand://provider",serde_json::json!({"provider":"azure-devops","count":out.len()})); Ok(out)}
#[tauri::command]
async fn sync_azure_activity(provider_url:String, db:State<'_,Db>, app:AppHandle)->Result<u32,String>{let token=provider_token("azure-devops").await?; let base=provider_url.trim_end_matches('/'); let response=reqwest::Client::new().get(format!("{base}/_apis/git/pullrequests?searchCriteria.status=all&api-version=7.1")).basic_auth("",Some(&token)).send().await.map_err(|e|e.to_string())?; if !response.status().is_success(){return Err(format!("Azure DevOps returned {}",response.status()))} let pulls:serde_json::Value=response.json().await.map_err(|e|e.to_string())?; let client=reqwest::Client::new(); let mut added=0; for pull in pulls["value"].as_array().cloned().unwrap_or_default(){let repo_id=pull["repository"]["id"].as_str().unwrap_or_default(); let project=pull["repository"]["project"]["id"].as_str().unwrap_or_default(); let pull_id=pull["pullRequestId"].as_i64().unwrap_or(0); if repo_id.is_empty()||project.is_empty()||pull_id==0{continue} let threads=client.get(format!("{base}/{project}/_apis/git/repositories/{repo_id}/pullRequests/{pull_id}/threads?api-version=7.1")).basic_auth("",Some(&token)).send().await.map_err(|e|e.to_string())?; let payload:serde_json::Value=threads.json().await.unwrap_or_default(); for thread in payload["value"].as_array().cloned().unwrap_or_default(){for comment in thread["comments"].as_array().cloned().unwrap_or_default(){let id=format!("azure:{}",comment["id"].as_i64().unwrap_or(0)); let conn=db.0.lock().map_err(|e|e.to_string())?; let changed=conn.execute("INSERT OR IGNORE INTO notifications(id,provider,repo,title,body,url,author,unread,created_at) VALUES (?1,'azure-devops',?2,?3,?4,?5,?6,1,?7)",params![id,pull["repository"]["name"].as_str().unwrap_or("Azure repository"),pull["title"].as_str().unwrap_or("Pull request comment"),comment["content"].as_str().unwrap_or_default(),pull["url"].as_str().unwrap_or_default(),comment["author"]["displayName"].as_str().unwrap_or("Azure DevOps"),comment["publishedDate"].as_str().unwrap_or_default()]).map_err(|e|e.to_string())?; if changed>0{added+=1;}}}} let _=app.emit("wand://notifications",serde_json::json!({"provider":"azure-devops","added":added})); Ok(added)}

async fn background_github_activity(db:Arc<Mutex<Connection>>, app:AppHandle){let token=match provider_token("github").await{Ok(value)=>value,Err(_)=>return}; let names:Vec<String>={let conn=match db.lock(){Ok(value)=>value,Err(_)=>return}; let mut stmt=match conn.prepare("SELECT name FROM repos WHERE provider='github'"){Ok(value)=>value,Err(_)=>return}; let rows=match stmt.query_map([],|r|r.get(0)){Ok(value)=>value,Err(_)=>return}; match rows.collect::<Result<Vec<String>,_>>(){Ok(value)=>value,Err(_)=>return}}; let client=reqwest::Client::new(); let mut added=0; for name in names{let response=match client.get(format!("https://api.github.com/repos/{name}/pulls/comments?per_page=50&sort=created&direction=desc")).header("User-Agent","Wand").bearer_auth(&token).send().await{Ok(value)=>value,Err(_)=>continue}; if !response.status().is_success(){continue} let comments:Vec<serde_json::Value>=match response.json().await{Ok(value)=>value,Err(_)=>continue}; for comment in comments{let id=format!("github-review:{}",comment["id"].as_i64().unwrap_or(0)); let conn=match db.lock(){Ok(value)=>value,Err(_)=>return}; let changed=conn.execute("INSERT OR IGNORE INTO notifications(id,provider,repo,title,body,url,author,unread,created_at) VALUES (?1,'github',?2,'Pull request review comment',?3,?4,?5,1,?6)",params![id,name,comment["body"].as_str().unwrap_or_default(),comment["html_url"].as_str().unwrap_or_default(),comment["user"]["login"].as_str().unwrap_or("GitHub"),comment["created_at"].as_str().unwrap_or_default()]); if changed.unwrap_or(0)>0{added+=1}}} if added>0{let _=app.emit("wand://notifications",serde_json::json!({"provider":"github","added":added,"background":true}));}}
async fn background_azure_activity(db:Arc<Mutex<Connection>>, app:AppHandle){let token=match provider_token("azure-devops").await{Ok(value)=>value,Err(_)=>return}; let base:Option<String>={let conn=match db.lock(){Ok(value)=>value,Err(_)=>return}; conn.query_row("SELECT url FROM provider_settings WHERE provider='azure-devops'",[],|r|r.get(0)).optional().ok().flatten()}; let Some(base)=base else{return}; let client=reqwest::Client::new(); let response=match client.get(format!("{base}/_apis/git/pullrequests?searchCriteria.status=all&api-version=7.1")).basic_auth("",Some(&token)).send().await{Ok(value)=>value,Err(_)=>return}; if !response.status().is_success(){return} let pulls:serde_json::Value=match response.json().await{Ok(value)=>value,Err(_)=>return}; let mut added=0; for pull in pulls["value"].as_array().cloned().unwrap_or_default(){let repo_id=pull["repository"]["id"].as_str().unwrap_or_default(); let project=pull["repository"]["project"]["id"].as_str().unwrap_or_default(); let pull_id=pull["pullRequestId"].as_i64().unwrap_or(0); if repo_id.is_empty()||project.is_empty()||pull_id==0{continue} let response=match client.get(format!("{base}/{project}/_apis/git/repositories/{repo_id}/pullRequests/{pull_id}/threads?api-version=7.1")).basic_auth("",Some(&token)).send().await{Ok(value)=>value,Err(_)=>continue}; let threads:serde_json::Value=match response.json().await{Ok(value)=>value,Err(_)=>continue}; for thread in threads["value"].as_array().cloned().unwrap_or_default(){for comment in thread["comments"].as_array().cloned().unwrap_or_default(){let id=format!("azure:{}",comment["id"].as_i64().unwrap_or(0)); let conn=match db.lock(){Ok(value)=>value,Err(_)=>return}; let changed=conn.execute("INSERT OR IGNORE INTO notifications(id,provider,repo,title,body,url,author,unread,created_at) VALUES (?1,'azure-devops',?2,?3,?4,?5,?6,1,?7)",params![id,pull["repository"]["name"].as_str().unwrap_or("Azure repository"),pull["title"].as_str().unwrap_or("Pull request comment"),comment["content"].as_str().unwrap_or_default(),pull["url"].as_str().unwrap_or_default(),comment["author"]["displayName"].as_str().unwrap_or("Azure DevOps"),comment["publishedDate"].as_str().unwrap_or_default()]); if changed.unwrap_or(0)>0{added+=1}}}} if added>0{let _=app.emit("wand://notifications",serde_json::json!({"provider":"azure-devops","added":added,"background":true}));}}

fn start_background_sync(app: AppHandle, db: Arc<Mutex<Connection>>) {
  thread::spawn(move || {
    let mut last_due: HashMap<String, String> = HashMap::new();
    loop {
      let now = Utc::now();
      if now.timestamp().rem_euclid(300) < 30 { let poll_db=db.clone(); let poll_app=app.clone(); tauri::async_runtime::spawn(async move { background_github_activity(poll_db.clone(),poll_app.clone()).await; background_azure_activity(poll_db,poll_app).await; }); }
      if let Ok(conn) = db.lock() {
        if let Ok(mut stmt) = conn.prepare("SELECT id,name,cron FROM tasks WHERE cron != 'one-off' AND status != 'completed'") {
          if let Ok(rows) = stmt.query_map([], |r| Ok((r.get::<_,String>(0)?, r.get::<_,String>(1)?, r.get::<_,String>(2)?))) {
            for row in rows.flatten() {
              let (id, name, expr) = row;
              if let Ok(schedule) = Schedule::from_str(&expr) {
                // Look back one polling window so a job is still detected when the
                // 30-second worker wakes just after the cron boundary.
                if let Some(next) = schedule.after(&(now - chrono::Duration::seconds(30))).next() {
                  let slot = next.to_rfc3339();
                  if next <= now && last_due.get(&id) != Some(&slot) {
                    last_due.insert(id.clone(), slot);
                    let message = format!("Scheduled task due: {name}");
                    let _ = conn.execute("INSERT INTO events(kind,message,created_at) VALUES (?1,?2,?3)", params!["scheduler.due", message, now.to_rfc3339()]);
                    let _ = app.emit("wand://scheduler", serde_json::json!({"task_id":id,"name":name,"status":"due","at":now.to_rfc3339()}));
                  }
                }
              }
            }
          }
        }
        let count: i64 = conn.query_row("SELECT COUNT(*) FROM tasks WHERE cron != 'one-off' AND status != 'completed'", [], |r| r.get(0)).unwrap_or(0);
        let event = SyncEvent { source: "scheduler".into(), message: format!("Background scheduler active — {count} recurring task(s) monitored"), timestamp: now.to_rfc3339() };
        let _ = app.emit("wand://sync", event);
      }
      thread::sleep(Duration::from_secs(30));
    }
  });
}
#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() { tauri::Builder::default().plugin(tauri_plugin_process::init()).plugin(tauri_plugin_updater::Builder::new().pubkey("dW50cnVzdGVkIGNvbW1lbnQ6IG1pbmlzaWduIHB1YmxpYyBrZXk6IDQyOTc2NzY4ODBFMDUzQ0QKUldUTlUrQ0FhR2VYUXJ3SFI0SytQbkIzaTBOaXdzWjNNYlNkb2dxLzdQdVJkcG9yZEhqeUQ0WUcK").build()).setup(|app| { let dir:PathBuf=app.path().app_data_dir().expect("app data dir"); fs::create_dir_all(&dir).expect("create app data dir"); let conn=Connection::open(dir.join("wand.db")).expect("open database"); migrate(&conn).expect("migrate database"); let db=Arc::new(Mutex::new(conn)); app.manage(Db(db.clone())); start_background_sync(app.handle().clone(),db); Ok(()) }).invoke_handler(tauri::generate_handler![run_agent_cli,run_agent_chain,create_task,list_tasks,list_thread_messages,create_thread_message,list_notifications,mark_notifications_read,detect_clis,save_provider_token,provider_status,save_provider_url,provider_url,sync_github,sync_github_activity,sync_azure_devops,sync_azure_activity]).run(tauri::generate_context!()).expect("error while running wand"); }
