import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { invoke } from '@tauri-apps/api/core';
import { listen } from '@tauri-apps/api/event';
import { check } from '@tauri-apps/plugin-updater';
import { relaunch } from '@tauri-apps/plugin-process';
import { Bell, Bot, CheckCircle2, ChevronDown, Clock3, Code2, FolderGit2, GitPullRequest, Github, Hash, LayoutDashboard, MessageSquare, Play, Plus, Search, Settings, Sparkles, TerminalSquare, TimerReset, Zap } from 'lucide-react';
import './styles.css';
import './layout.css';
import './theme.css';

type View = 'home'|'threads'|'tasks'|'notifications'|'settings';
type Repo = { name:string; path:string; color:string; count:number };
type Agent = { id:string; name:string; role:string; skills:string[]; color:string };
type Task = { id:string; name:string; provider:string; repo:string; cron:string; active:boolean; agents:string[] };
const defaultRepos:Repo[] = [{name:'wand',path:'~/Code/wand',color:'#89b4fa',count:4},{name:'api-gateway',path:'~/Code/api-gateway',color:'#cba6f7',count:2},{name:'design-system',path:'~/Code/design-system',color:'#f9e2af',count:1}];
const agents:Agent[] = [{id:'planner',name:'Planner',role:'Breaks work into executable slices',skills:['planning','repo analysis'],color:'#a98cff'},{id:'builder',name:'Builder',role:'Implements features and fixes',skills:['typescript','rust','testing'],color:'#76c6f5'},{id:'reviewer',name:'Code reviewer',role:'Reviews changes and suggests fixes',skills:['code review','security'],color:'#f9c86a'},{id:'sentinel',name:'Sentinel',role:'Runs verification in the background',skills:['ci','dependency audit','regression'],color:'#6fdaa0'},{id:'docs',name:'Docs writer',role:'Keeps technical docs current',skills:['documentation','changelog'],color:'#f38ba8'}];
const defaultTasks:Task[] = [{id:'weekly-audit',name:'Weekly dependency audit',provider:'Agent chain',repo:'api-gateway',cron:'0 9 * * 1',active:true,agents:['sentinel']}];
const load = <T,>(key:string, fallback:T):T => { try { return JSON.parse(localStorage.getItem(key) || '') as T } catch { return fallback } };

function App(){
  const [view,setView]=useState<View>('home'); const [repos,setRepos]=useState(()=>load('forgepad.repos',defaultRepos)); const [tasks,setTasks]=useState(()=>load('forgepad.tasks',defaultTasks)); const [repo,setRepo]=useState(repos[0]); const [query,setQuery]=useState(''); const [notice,setNotice]=useState('');
  useEffect(()=>localStorage.setItem('forgepad.repos',JSON.stringify(repos)),[repos]); useEffect(()=>localStorage.setItem('forgepad.tasks',JSON.stringify(tasks)),[tasks]);
  useEffect(()=>{let stop:undefined|(()=>void); listen<{message:string}>('wand://sync',e=>setNotice(e.payload.message)).then(unlisten=>stop=unlisten); return ()=>stop?.()},[]);
  useEffect(()=>{check().then(async update=>{if(update && window.confirm(`Wand ${update.version} is available. Download and install it now?`)){setNotice(`Downloading Wand ${update.version}…`); await update.downloadAndInstall(); await relaunch()}}).catch(()=>{/* Browser dev mode has no updater plugin. */})},[]);
  const addRepo=()=>{const name=prompt('Repository name'); if(!name)return; const path=prompt('Local folder path','~/Code/'+name); if(!path)return; const next={name,path,color:'#89b4fa',count:0}; setRepos([...repos,next]); setRepo(next); setView('threads');};
  const addTask=()=>{const name=prompt('Task name','Implement the next feature'); if(!name)return; const selected=agents.filter(a=>confirm(`Tag ${a.name} for this task?`)).map(a=>a.id); const cron=prompt('Cron expression (leave blank for one-off)',''); setTasks([...tasks,{id:crypto.randomUUID(),name,provider:'Agent chain',repo:repo.name,cron:cron||'one-off',active:true,agents:selected.length?selected:['planner','builder','reviewer','sentinel']}]); setNotice('Task saved with an agent handoff chain'); setView('tasks');};
  const runTask=async(t:Task)=>{const chain=t.agents.map(id=>agents.find(a=>a.id===id)?.name).filter(Boolean).join(' → '); try {const result=await invoke<{message:string}>('run_agent_cli',{provider:'agent-chain',prompt:`${t.name}\nHandoff chain: ${chain}\nThe final Sentinel agent must verify the complete result in the background.`,repoPath:repos.find(r=>r.name===t.repo)?.path||''}); setNotice(result.message)} catch {setNotice(`Queued: ${chain}. Sentinel will verify in background when running under Tauri.`)}};
  const nav=(v:View)=><button className={view===v?'nav active':'nav'} onClick={()=>setView(v)}>{v==='home'?<LayoutDashboard/>:v==='threads'?<MessageSquare/>:v==='tasks'?<Clock3/>:v==='notifications'?<Bell/>:<Settings/>}<span>{v[0].toUpperCase()+v.slice(1)}</span>{v==='notifications'&&<b className="badge">3</b>}</button>;
  return <div className="app"><aside><div className="brand"><div className="mark"><Sparkles size={17}/></div><span>forgepad</span><small>private beta</small></div><div className="workspace"><div className="avatar">VC</div><div><strong>Venkata's space</strong><small>Personal workspace</small></div><ChevronDown size={15}/></div><div className="navgroup"><label>Workspace</label>{nav('home')}{nav('threads')}{nav('tasks')}{nav('notifications')}</div><div className="navgroup repos"><label>Repositories <button className="sideplus" onClick={addRepo}><Plus size={13}/></button></label>{repos.map(r=><button key={r.name} className={'repo '+(repo.name===r.name?'selected':'')} onClick={()=>{setRepo(r);setView('threads')}}><i style={{background:r.color}}/><span>{r.name}</span><em>{r.count}</em></button>)}</div><div className="bottom">{nav('settings')}<div className="status"><span/> Local workspace ready</div></div></aside><main><header><div className="crumb"><span>Workspace</span><b>/</b><strong>{view==='home'?'Overview':view==='threads'?repo.name:view[0].toUpperCase()+view.slice(1)}</strong></div><div className="actions"><div className="search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search anything"/><kbd>⌘ K</kbd></div><button className="iconbtn"><Bell size={17}/><i/></button><div className="avatar">VC</div></div></header>{notice&&<button className="toast" onClick={()=>setNotice('')}>{notice} ×</button>}{view==='home'?<Home setView={setView}/>:view==='threads'?<Threads repo={repo}/>:view==='tasks'?<Tasks tasks={tasks} addTask={addTask} runTask={runTask}/>:view==='notifications'?<Notifications/>:<SettingsView repos={repos}/>}</main></div>
}
function Home({setView}:{setView:(v:View)=>void}){return <section className="content"><div className="hero"><div><p className="eyebrow"><span className="pulse"/> LOCAL WORKSPACE</p><h1>Good morning, Venkata.</h1><p className="sub">Your agents are ready to work across your repositories.</p></div><button className="primary" onClick={()=>setView('tasks')}><Plus size={16}/> New task</button></div><div className="stats"><Stat icon={Zap} value="12" label="Agent runs today" hint="Local activity log"/><Stat icon={GitPullRequest} value="4" label="PRs need your eyes" hint="Across 2 repositories"/><Stat icon={TimerReset} value="2h 48m" label="Time saved" hint="By your agents this week"/></div><div className="sectionhead"><div><h2>Activity</h2><p>Events synced to this local workspace.</p></div></div><div className="timeline">{['Improve agent run timeline','Weekly dependency audit','Should tokens live in a separate package?','Can we make this state recoverable?'].map((x,i)=><article className="event" key={x}><div className={'eventicon '+(['purple','green','yellow','blue'][i])}>{i===1?<CheckCircle2 size={17}/>:i>1?<MessageSquare size={17}/>:<GitPullRequest size={17}/>}</div><div className="eventbody"><div className="eventtop"><span className="kind">{i===1?'Agent completed':i>1?'PR comment':'PR review'}</span><span className="tag blue">{i===1?'passed':'needs review'}</span><span className="time">{i+1}h ago</span></div><h3>{x}</h3><p><span className="repo-dot"/> forgepad · {i===1?'Sentinel':'Code reviewer'}</p></div></article>)}</div><div className="sectionhead agents"><div><h2>Active agents</h2><p>Configured coding specialists.</p></div><button className="textbtn" onClick={()=>setView('settings')}>Manage agents →</button></div><div className="agentgrid"><Agent icon={Bot} name="Code reviewer" desc="Reviews new pull requests" status="Watching your repos"/><Agent icon={TerminalSquare} name="Sentinel" desc="Dependency & security audits" status="Schedule available"/><Agent icon={Code2} name="Pair programmer" desc="Your on-demand coding partner" status="Ready when you are"/></div></section>}
function Stat({icon:Icon,value,label,hint}:{icon:any,value:string,label:string,hint:string}){return <div className="stat"><Icon size={18}/><strong>{value}</strong><span>{label}</span><small>{hint}</small></div>} function Agent({icon:Icon,name,desc,status}:{icon:any,name:string,desc:string,status:string}){return <div className="agent"><div className="agenticon"><Icon size={18}/></div><div><h3>{name}</h3><p>{desc}</p><small><span className="green-dot"/> {status}</small></div></div>}
function Threads({repo}:{repo:Repo}){return <section className="content"><div className="hero compact"><div><p className="eyebrow"><FolderGit2 size={14}/> REPOSITORY</p><h1>{repo.name}</h1><p className="sub">Threads and agent context for {repo.path}</p></div><button className="primary" onClick={()=>alert('Thread creation is next: the local thread store is ready for wiring.')}><Plus size={16}/> New thread</button></div><div className="threadlist">{['Make the deploy preview recoverable','Improve agent run timeline','Release checklist · v2.4.0','Pair on auth middleware'].map((x,i)=><div className="thread" key={x}><div className="threadicon"><Hash size={16}/></div><div><h3>{x}</h3><p>{i%2?'Maya Chen':'Code reviewer'} · {i+1} days ago</p></div><span className="tag blue">{i+1} replies</span><ChevronDown size={16}/></div>)}</div></section>}
function Tasks({tasks,addTask,runTask}:{tasks:Task[],addTask:()=>void,runTask:(t:Task)=>void}){return <section className="content"><div className="hero compact"><div><p className="eyebrow"><Clock3 size={14}/> AUTOMATIONS</p><h1>Scheduled tasks</h1><p className="sub">Persisted locally and ready for agent execution.</p></div><button className="primary" onClick={addTask}><Plus size={16}/> Schedule task</button></div>{tasks.map(t=><div className="taskcard" key={t.id}><div className="taskicon"><Zap size={17}/></div><div><h3>{t.name}</h3><p>{t.provider} · {t.repo}</p></div><code>{t.cron}</code><span className="tag green">{t.active?'Active':'Paused'}</span><button className="run" onClick={()=>runTask(t)}><Play size={14}/> Run now</button></div>)}<div className="emptyhint"><Sparkles size={20}/><h3>Agent execution boundary</h3><p>Run now calls the Tauri command boundary with provider, prompt, and repo path. Wire each CLI as a sidecar next.</p></div></section>}
function Notifications(){return <section className="content"><div className="hero compact"><div><p className="eyebrow"><Bell size={14}/> INBOX</p><h1>Notifications</h1><p className="sub">PR comments and agent events that need your attention.</p></div><button className="textbtn">Mark all read</button></div><div className="notice"><div className="eventicon purple"><MessageSquare size={17}/></div><div><b>PR comment inbox is ready for provider sync</b><p>Connect GitHub or Azure DevOps in Settings to import comments.</p></div><span>setup</span></div></section>}
function SettingsView({repos}:{repos:Repo[]}){return <section className="content"><div className="hero compact"><div><p className="eyebrow"><Settings size={14}/> PREFERENCES</p><h1>Settings</h1><p className="sub">Configure providers and the local repository workspace.</p></div></div><div className="settingscard"><h2>Connected providers</h2><p>Tokens will be stored in the OS keychain through Tauri.</p><div className="provider"><Github size={19}/><div><b>GitHub</b><small>Personal access token · Ready for connection</small></div><button className="outline" onClick={()=>alert('GitHub PAT flow: add encrypted keychain storage next.')}>Connect</button></div><div className="provider"><GitPullRequest size={19}/><div><b>Azure DevOps</b><small>Personal access token · Ready for connection</small></div><button className="outline">Connect</button></div><h2 className="space">Repository folder</h2><div className="folder"><FolderGit2 size={18}/><span>{repos.length} repositories in local workspace</span><button className="outline">Choose folder</button></div></div></section>}
function Onboarding({done}:{done:()=>void}){const [step,setStep]=useState(0); const slides=[['Welcome to Wand','Your local-first AI engineering workspace. Plan, build, review, and verify without losing the thread.'],['Connect your workspace','Choose a repository folder, then connect GitHub or Azure DevOps with a PAT when you are ready.'],['Meet your agent team','Tag Planner, Builder, Reviewer, Docs, and Sentinel on any task. Each agent hands work to the next.'],['You stay in control','Wand keeps work local, shows every handoff, and runs a final background verification before calling work done.']]; const current=slides[step]; return <div className="onboarding"><div className="onboard-card"><div className="onboard-mark">✦</div><p className="eyebrow">WAND / GETTING STARTED</p><h1>{current[0]}</h1><p>{current[1]}</p><div className="onboard-dots">{slides.map((_,i)=><i className={i===step?'on':''} key={i}/>)}</div><div className="onboard-actions">{step>0?<button className="textbtn" onClick={()=>setStep(step-1)}>Back</button>:<span/>}<button className="primary" onClick={()=>step<slides.length-1?setStep(step+1):done()}>{step<slides.length-1?'Continue':'Enter Wand'}</button></div></div></div>}
function ThemePicker(){const [theme,setTheme]=useState(()=>localStorage.getItem('wand.theme')||'obsidian'); useEffect(()=>{document.body.dataset.theme=theme;localStorage.setItem('wand.theme',theme)},[theme]); return <div className="theme-dock"><span className="theme-label">Theme</span>{['obsidian','aurora','amethyst','ember'].map(name=><button aria-label={name+' theme'} className={'theme-choice '+name+(theme===name?' active':'')} onClick={()=>setTheme(name)} key={name}/>)}</div>}
function OnboardingGate(){const [show,setShow]=useState(()=>localStorage.getItem('wand.onboarding.complete')!=='true'); const finish=()=>{localStorage.setItem('wand.onboarding.complete','true');setShow(false)}; return <><App/><ThemePicker/>{show&&<Onboarding done={finish}/>}</>}
createRoot(document.getElementById('root')!).render(<OnboardingGate/>);
