import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { invoke } from '@tauri-apps/api/core';
import { listen } from '@tauri-apps/api/event';
import { check } from '@tauri-apps/plugin-updater';
import { relaunch } from '@tauri-apps/plugin-process';
import { Bell, Bot, CheckCircle2, ChevronDown, Clock3, Code2, FolderGit2, GitPullRequest, Github, Hash, LayoutDashboard, MessageSquare, Play, Plus, Search, Settings, Sparkles, TerminalSquare, TimerReset, Zap } from 'lucide-react';
import './styles.css';
import './layout.css';
import './theme.css';
import './premium.css';
import './account.css';
import './chrome-redesign.css';
import './chrome-fixes.css';
import './ui-corrections.css';
import './provider-ui.css';
import './responsive-fix.css';

type View = 'home'|'threads'|'tasks'|'notifications'|'settings';
type Repo = { name:string; path:string; color:string; count:number };
type Agent = { id:string; name:string; role:string; skills:string[]; color:string };
type Task = { id:string; name:string; provider:string; repo:string; cron:string; active:boolean; agents:string[] };
const defaultRepos:Repo[] = [{name:'wand',path:'~/Code/wand',color:'#89b4fa',count:4},{name:'api-gateway',path:'~/Code/api-gateway',color:'#cba6f7',count:2},{name:'design-system',path:'~/Code/design-system',color:'#f9e2af',count:1}];
const agents:Agent[] = [{id:'planner',name:'Planner',role:'Breaks work into executable slices',skills:['planning','repo analysis'],color:'#a98cff'},{id:'builder',name:'Builder',role:'Implements features and fixes',skills:['typescript','rust','testing'],color:'#76c6f5'},{id:'reviewer',name:'Code reviewer',role:'Reviews changes and suggests fixes',skills:['code review','security'],color:'#f9c86a'},{id:'sentinel',name:'Sentinel',role:'Runs verification in the background',skills:['ci','dependency audit','regression'],color:'#6fdaa0'},{id:'docs',name:'Docs writer',role:'Keeps technical docs current',skills:['documentation','changelog'],color:'#f38ba8'}];
const defaultTasks:Task[] = [{id:'weekly-audit',name:'Weekly dependency audit',provider:'Agent chain',repo:'api-gateway',cron:'0 9 * * 1',active:true,agents:['sentinel']}];
const load = <T,>(key:string, fallback:T):T => { try { return JSON.parse(localStorage.getItem(key) || '') as T } catch { return fallback } };

function App(){
  const [view,setView]=useState<View>('home'); const [repos,setRepos]=useState(()=>load('wand.repos',defaultRepos)); const [tasks,setTasks]=useState(()=>load('wand.tasks',defaultTasks)); const [repo,setRepo]=useState(repos[0]); const [query,setQuery]=useState(''); const [notice,setNotice]=useState('');
  useEffect(()=>localStorage.setItem('wand.repos',JSON.stringify(repos)),[repos]); useEffect(()=>localStorage.setItem('wand.tasks',JSON.stringify(tasks)),[tasks]);
  useEffect(()=>{invoke<any[]>('list_tasks').then(rows=>{if(rows.length)setTasks(rows.map(r=>({...r,provider:'Agent chain',active:r.status!=='failed',agents:JSON.parse(r.agents||'[]')})))}).catch(()=>{})},[]);
  useEffect(()=>{let stop:undefined|(()=>void); listen<{message:string}>('wand://sync',e=>setNotice(e.payload.message)).then(unlisten=>stop=unlisten); return ()=>stop?.()},[]);
  useEffect(()=>{document.body.dataset.view=view; const go=(e:Event)=>setView((e as CustomEvent<View>).detail); window.addEventListener('wand:navigate',go); return ()=>window.removeEventListener('wand:navigate',go)},[view]);
  useEffect(()=>{check().then(async update=>{if(update && window.confirm(`Wand ${update.version} is available. Download and install it now?`)){setNotice(`Downloading Wand ${update.version}…`); await update.downloadAndInstall(); await relaunch()}}).catch(()=>{/* Browser dev mode has no updater plugin. */})},[]);
  const addRepo=()=>{const name=prompt('Repository name'); if(!name)return; const path=prompt('Local folder path','~/Code/'+name); if(!path)return; const next={name,path,color:'#89b4fa',count:0}; setRepos([...repos,next]); setRepo(next); setView('threads');};
  const addTask=()=>{const name=prompt('Task name','Implement the next feature'); if(!name)return; const selected=agents.filter(a=>confirm(`Tag ${a.name} for this task?`)).map(a=>a.id); const cron=prompt('Cron expression (leave blank for one-off)',''); const task={id:crypto.randomUUID(),name,provider:'Agent chain',repo:repo.name,cron:cron||'one-off',active:true,agents:selected.length?selected:['planner','builder','reviewer','sentinel']}; setTasks([...tasks,task]); invoke('create_task',{task:{id:task.id,name:task.name,repo:task.repo,cron:task.cron,agents:task.agents}}).catch(()=>{}); setNotice('Task saved with an agent handoff chain'); setView('tasks');};
  const runTask=async(t:Task)=>{const chain=t.agents.map(id=>agents.find(a=>a.id===id)?.name).filter(Boolean).join(' → '); const enabled=JSON.parse(localStorage.getItem('wand.clis')||'[]'); const cli=enabled[0]||'codex'; try {await invoke('run_agent_chain',{req:{task_id:t.id,prompt:`${t.name}\nHandoff chain: ${chain}\nThe final Sentinel agent must verify the complete result in the background.`,repo_path:repos.find(r=>r.name===t.repo)?.path||'.',agents:t.agents,cli}}); setNotice(`Started ${chain} using ${cli}`)} catch {setNotice(`Queued: ${chain}. Enable a local CLI in Settings to execute it.`)}};
  const nav=(v:View)=><button className={view===v?'nav active':'nav'} onClick={()=>setView(v)}>{v==='home'?<LayoutDashboard/>:v==='threads'?<MessageSquare/>:v==='tasks'?<Clock3/>:v==='notifications'?<Bell/>:<Settings/>}<span>{v[0].toUpperCase()+v.slice(1)}</span>{v==='notifications'&&<b className="badge">3</b>}</button>;
  return <div className="app"><aside><div className="brand"><div className="mark"><Sparkles size={17}/></div><span>wand</span><small>private beta</small></div><div className="workspace"><div className="avatar">VC</div><div><strong>Venkata's space</strong><small>Personal workspace</small></div><ChevronDown size={15}/></div><div className="navgroup"><label>Workspace</label>{nav('home')}{nav('threads')}{nav('tasks')}{nav('notifications')}</div><div className="navgroup repos"><label>Repositories <button className="sideplus" onClick={addRepo}><Plus size={13}/></button></label>{repos.map(r=><button key={r.name} className={'repo '+(repo.name===r.name?'selected':'')} onClick={()=>{setRepo(r);setView('threads')}}><i style={{background:r.color}}/><span>{r.name}</span><em>{r.count}</em></button>)}</div><div className="bottom">{nav('settings')}<div className="status"><span/> Local workspace ready</div></div></aside><main><header><div className="crumb"><span>Workspace</span><b>/</b><strong>{view==='home'?'Overview':view==='threads'?repo.name:view[0].toUpperCase()+view.slice(1)}</strong></div><div className="actions"><div className="search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search anything"/><kbd>⌘ K</kbd></div><button className="iconbtn"><Bell size={17}/><i/></button><div className="avatar">VC</div></div></header>{notice&&<button className="toast" onClick={()=>setNotice('')}>{notice} ×</button>}{view==='home'?<Home setView={setView}/>:view==='threads'?<Threads repo={repo}/>:view==='tasks'?<Tasks tasks={tasks} addTask={addTask} runTask={runTask}/>:view==='notifications'?<Notifications/>:<SettingsView repos={repos}/>}</main><RepoChat repo={repo.name}/></div>
}
function Home({setView}:{setView:(v:View)=>void}){return <section className="content"><div className="hero"><div><p className="eyebrow"><span className="pulse"/> LOCAL WORKSPACE</p><h1>Good morning, Venkata.</h1><p className="sub">Your agents are ready to work across your repositories.</p></div><button className="primary" onClick={()=>setView('tasks')}><Plus size={16}/> New task</button></div><div className="stats"><Stat icon={Zap} value="12" label="Agent runs today" hint="Local activity log"/><Stat icon={GitPullRequest} value="4" label="PRs need your eyes" hint="Across 2 repositories"/><Stat icon={TimerReset} value="2h 48m" label="Time saved" hint="By your agents this week"/></div><div className="sectionhead"><div><h2>Activity</h2><p>Events synced to this local workspace.</p></div></div><div className="timeline">{['Improve agent run timeline','Weekly dependency audit','Should tokens live in a separate package?','Can we make this state recoverable?'].map((x,i)=><article className="event" key={x}><div className={'eventicon '+(['purple','green','yellow','blue'][i])}>{i===1?<CheckCircle2 size={17}/>:i>1?<MessageSquare size={17}/>:<GitPullRequest size={17}/>}</div><div className="eventbody"><div className="eventtop"><span className="kind">{i===1?'Agent completed':i>1?'PR comment':'PR review'}</span><span className="tag blue">{i===1?'passed':'needs review'}</span><span className="time">{i+1}h ago</span></div><h3>{x}</h3><p><span className="repo-dot"/> wand · {i===1?'Sentinel':'Code reviewer'}</p></div></article>)}</div><div className="sectionhead agents"><div><h2>Active agents</h2><p>Configured coding specialists.</p></div><button className="textbtn" onClick={()=>setView('settings')}>Manage agents →</button></div><div className="agentgrid"><Agent icon={Bot} name="Code reviewer" desc="Reviews new pull requests" status="Watching your repos"/><Agent icon={TerminalSquare} name="Sentinel" desc="Dependency & security audits" status="Schedule available"/><Agent icon={Code2} name="Pair programmer" desc="Your on-demand coding partner" status="Ready when you are"/></div></section>}
function Stat({icon:Icon,value,label,hint}:{icon:any,value:string,label:string,hint:string}){return <div className="stat"><Icon size={18}/><strong>{value}</strong><span>{label}</span><small>{hint}</small></div>} function Agent({icon:Icon,name,desc,status}:{icon:any,name:string,desc:string,status:string}){return <div className="agent"><div className="agenticon"><Icon size={18}/></div><div><h3>{name}</h3><p>{desc}</p><small><span className="green-dot"/> {status}</small></div></div>}
function Threads({repo}:{repo:Repo}){return <section className="content"><div className="hero compact"><div><p className="eyebrow"><FolderGit2 size={14}/> REPOSITORY</p><h1>{repo.name}</h1><p className="sub">Threads and agent context for {repo.path}</p></div><button className="primary" onClick={()=>alert('Thread creation is next: the local thread store is ready for wiring.')}><Plus size={16}/> New thread</button></div><div className="threadlist">{['Make the deploy preview recoverable','Improve agent run timeline','Release checklist · v2.4.0','Pair on auth middleware'].map((x,i)=><div className="thread" key={x}><div className="threadicon"><Hash size={16}/></div><div><h3>{x}</h3><p>{i%2?'Maya Chen':'Code reviewer'} · {i+1} days ago</p></div><span className="tag blue">{i+1} replies</span><ChevronDown size={16}/></div>)}</div></section>}
function Tasks({tasks,addTask,runTask}:{tasks:Task[],addTask:()=>void,runTask:(t:Task)=>void}){return <section className="content"><div className="hero compact"><div><p className="eyebrow"><Clock3 size={14}/> AUTOMATIONS</p><h1>Scheduled tasks</h1><p className="sub">Persisted locally and ready for agent execution.</p></div><button className="primary" onClick={addTask}><Plus size={16}/> Schedule task</button></div>{tasks.map(t=><div className="taskcard" key={t.id}><div className="taskicon"><Zap size={17}/></div><div><h3>{t.name}</h3><p>{t.provider} · {t.repo}</p></div><code>{t.cron}</code><span className="tag green">{t.active?'Active':'Paused'}</span><button className="run" onClick={()=>runTask(t)}><Play size={14}/> Run now</button></div>)}<div className="emptyhint"><Sparkles size={20}/><h3>Agent execution boundary</h3><p>Run now calls the Tauri command boundary with provider, prompt, and repo path. Wire each CLI as a sidecar next.</p></div></section>}
function Notifications(){return <section className="content"><div className="hero compact"><div><p className="eyebrow"><Bell size={14}/> INBOX</p><h1>Notifications</h1><p className="sub">PR comments and agent events that need your attention.</p></div><button className="textbtn">Mark all read</button></div><div className="notice"><div className="eventicon purple"><MessageSquare size={17}/></div><div><b>PR comment inbox is ready for provider sync</b><p>Connect GitHub or Azure DevOps in Settings to import comments.</p></div><span>setup</span></div></section>}
function SettingsView({repos}:{repos:Repo[]}){return <section className="content"><div className="hero compact"><div><p className="eyebrow"><Settings size={14}/> PREFERENCES</p><h1>Settings</h1><p className="sub">Configure providers and the local repository workspace.</p></div></div><div className="settingscard"><h2>Connected providers</h2><p>Tokens will be stored in the OS keychain through Tauri.</p><div className="provider"><Github size={19}/><div><b>GitHub</b><small>Personal access token · Ready for connection</small></div><button className="outline" onClick={()=>alert('GitHub PAT flow: add encrypted keychain storage next.')}>Connect</button></div><div className="provider"><GitPullRequest size={19}/><div><b>Azure DevOps</b><small>Personal access token · Ready for connection</small></div><button className="outline">Connect</button></div><h2 className="space">Repository folder</h2><div className="folder"><FolderGit2 size={18}/><span>{repos.length} repositories in local workspace</span><button className="outline">Choose folder</button></div></div></section>}
function Onboarding({done}:{done:()=>void}){const [step,setStep]=useState(0); const slides=[['Welcome to Wand','Your local-first AI engineering workspace. Plan, build, review, and verify without losing the thread.'],['Connect your workspace','Choose a repository folder, then connect GitHub or Azure DevOps with a PAT when you are ready.'],['Meet your agent team','Tag Planner, Builder, Reviewer, Docs, and Sentinel on any task. Each agent hands work to the next.'],['You stay in control','Wand keeps work local, shows every handoff, and runs a final background verification before calling work done.']]; const current=slides[step]; return <div className="onboarding"><div className="onboard-card"><div className="onboard-mark">✦</div><p className="eyebrow">WAND / GETTING STARTED</p><h1>{current[0]}</h1><p>{current[1]}</p><div className="onboard-dots">{slides.map((_,i)=><i className={i===step?'on':''} key={i}/>)}</div><div className="onboard-actions">{step>0?<button className="textbtn" onClick={()=>setStep(step-1)}>Back</button>:<span/>}<button className="primary" onClick={()=>step<slides.length-1?setStep(step+1):done()}>{step<slides.length-1?'Continue':'Enter Wand'}</button></div></div></div>}
function ThemePicker(){const [theme,setTheme]=useState(()=>localStorage.getItem('wand.theme')||'obsidian'); useEffect(()=>{document.body.dataset.theme=theme;localStorage.setItem('wand.theme',theme)},[theme]); return <div className="theme-dock"><span className="theme-label">Appearance</span>{['obsidian','aurora','amethyst','ember'].map(name=><button aria-label={name+' theme'} className={'theme-choice '+name+(theme===name?' active':'')} onClick={()=>setTheme(name)} key={name}/>)}</div>}
function CliManager(){const [clis,setClis]=useState<any[]>([]); const [enabled,setEnabled]=useState<string[]>(()=>JSON.parse(localStorage.getItem('wand.clis')||'[]')); useEffect(()=>{invoke<any[]>('detect_clis').then(setClis).catch(()=>setClis([{id:'claude',name:'Claude',command:'claude',installed:false},{id:'codex',name:'Codex',command:'codex',installed:false},{id:'kimi',name:'Kimi',command:'kimi',installed:false},{id:'gemini',name:'Gemini CLI',command:'gemini',installed:false}]))},[]); const toggle=(id:string)=>{const next=enabled.includes(id)?enabled.filter(x=>x!==id):[...enabled,id];setEnabled(next);localStorage.setItem('wand.clis',JSON.stringify(next))}; return <div className="cli-manager"><div className="sectionhead"><div><h2>Local CLI access</h2><p>Choose which coding runtimes Wand may use.</p></div></div>{clis.map(c=><div className="cli-row" key={c.id}><div className={'cli-state '+(c.installed?'ready':'missing')}/><div><b>{c.name}</b><small>{c.installed?c.version||'Installed and detected':`Install “${c.command}” to enable`}</small></div><button className={'outline '+(enabled.includes(c.id)?'enabled':'')} disabled={!c.installed} onClick={()=>toggle(c.id)}>{enabled.includes(c.id)?'Enabled':'Enable'}</button></div>)}</div>}
function ProviderAccess(){const [status,setStatus]=useState<Record<string,boolean>>({}); const [syncing,setSyncing]=useState(''); const [message,setMessage]=useState(''); const refresh=()=>Promise.all(['github','azure-devops'].map(async p=>[p,await invoke<boolean>('provider_status',{provider:p}).catch(()=>false)] as const)).then(x=>setStatus(Object.fromEntries(x))); useEffect(()=>{refresh()},[]); const connect=async(provider:string)=>{const token=prompt(`Paste your ${provider} PAT. It will be stored in the OS credential store.`); if(!token)return; await invoke('save_provider_token',{provider,token}); refresh()}; const sync=async(provider:string)=>{try{setSyncing(provider);setMessage('');const args=provider==='azure-devops'?{providerUrl:prompt('Azure DevOps organization URL','https://dev.azure.com/your-org')||''}:{};if(provider==='azure-devops'&&!args.providerUrl)return;const rows=await invoke<any[]>(provider==='github'?'sync_github':'sync_azure_devops',args);setMessage(`${rows.length} ${provider==='github'?'GitHub':'Azure DevOps'} repositories synced.`)}catch(e){setMessage(String(e))}finally{setSyncing('')}}; return <div className="provider-access"><div className="sectionhead"><div><h2>Provider credentials</h2><p>Tokens never enter the React layer after submission.</p></div></div>{[['github','GitHub'],['azure-devops','Azure DevOps']].map(([id,name])=><div className="provider-row" key={id}><div><b>{name}</b><small>{status[id]?'Connected in OS credential store':'Not connected'}</small></div><button className="outline" onClick={()=>connect(id)}>{status[id]?'Replace PAT':'Connect'}</button><button className="outline" disabled={!status[id]||!!syncing} onClick={()=>sync(id)}>{syncing===id?'Syncing…':'Sync repos'}</button></div>)}{message&&<p className="provider-message">{message}</p>}</div>}
function RepoChat({repo}:{repo:string}){type Message={id?:number;repo?:string;author:string;body:string}; const [messages,setMessages]=useState<Message[]>([]); const [draft,setDraft]=useState(''); const [error,setError]=useState(''); useEffect(()=>{invoke<Message[]>('list_thread_messages',{repo}).then(setMessages).catch(()=>setMessages([]))},[repo]); useEffect(()=>{const stop=listen<Message>('wand://thread',e=>{if(e.payload.repo===repo)setMessages(current=>current.some(m=>m.id===e.payload.id)?current:[...current,e.payload])});return()=>{stop.then(fn=>fn())}},[repo]); const send=async()=>{const body=draft.trim();if(!body)return;try{const message=await invoke<Message>('create_thread_message',{repo,author:'You',body});setMessages(current=>current.some(m=>m.id===message.id)?current:[...current,message]);setDraft('');setError('')}catch(e){setError(String(e))}}; return <div className="repo-chat"><div className="chat-head"><div><b>{repo} thread</b><small>Humans and agents · persisted locally</small></div><span className="live-dot"/></div><div className="chat-messages">{messages.length===0&&<p className="chat-empty">Start the repository conversation.</p>}{messages.map((m,i)=><div className={'chat-message '+(m.author==='You'?'mine':'')} key={m.id??i}><small>{m.author}</small><p>{m.body}</p></div>)}</div><div className="chat-compose"><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Message this repository…"/><button onClick={send}>Send</button></div>{error&&<small className="chat-error">{error}</small>}</div>}
function AccountMenu(){const [open,setOpen]=useState(false); return <div className="account-menu"><button className="account-trigger" onClick={()=>setOpen(!open)}><span className="avatar">VC</span><span>Venkata</span><ChevronDown size={14}/></button>{open&&<div className="account-dropdown"><strong>Venkata's space</strong><small>Personal workspace</small><hr/><button onClick={()=>{window.dispatchEvent(new CustomEvent('wand:navigate',{detail:'settings'}));setOpen(false)}}><Settings size={14}/> Settings</button><button onClick={()=>setOpen(false)}><Sparkles size={14}/> What's new</button></div>}</div>}
function OnboardingGate(){const [show,setShow]=useState(()=>localStorage.getItem('wand.onboarding.complete')!=='true'); const finish=()=>{localStorage.setItem('wand.onboarding.complete','true');setShow(false)}; return <><App/><ThemePicker/><AccountMenu/><CliManager/><ProviderAccess/>{show&&<Onboarding done={finish}/>}</>}
createRoot(document.getElementById('root')!).render(<OnboardingGate/>);
